services:
  - type: web
    name: telegram-image-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 main:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-images-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: BASE_URL
        value: https://telegram-image-bot.onrender.com

databases:
  - name: telegram-images-db
    databaseName: telegram_images
    user: telegram_user
    plan: free